### ISSUE TITLE
Display a message to user when he/she types any invalid number 

### ISSUE THREAD

**Issue by Frey0xD** [Frey0xD/hacktoberfest#3]
in the last lines of the code "else" the statement

**Comment by DerMoehre** [comment]
I think, you don't need the last else statement, because the invalid number is catched within the try:except block. 
The else statement is no longer needed. Should I remove the else statement and push it to another PR?

**Comment by LastDeadlock** [comment]
Sure that will do the trick

**Comment by LastDeadlock** [comment]
sure that will do the trick

**Comment by DerMoehre** [comment]
added this to PR#5 :)

**Comment by RommelTJ** [comment]
This issue was resolved in https://github.com/LastDeadlock/hacktoberfest/pull/5.
