### ISSUE TITLE
Add another simple game in any language 

### ISSUE THREAD

**Issue by Frey0xD** [Frey0xD/hacktoberfest#9]
this repo already have one simple game in python so if you want to add another game in it you are always welcome

**Comment by Gaurika-Gupta** [comment]
Can I add a brick breaker game in Java? Please assign me this issue under Hacktoberfest 2022

**Comment by LastDeadlock** [comment]
Sure, any game 🎯 in any language is welcome.

**Comment by Talardork** [comment]
can i add hangman (word game) in python ?

**Comment by Frey0xD** [comment]
> can i add hangman (word game) in python ?

Sure but it would be nice if we make some new games this time

**Comment by Talardork** [comment]
sure, i'll be working on it. 
by the way, i have attached a pull request for the hangman game.
and i'll try to make some games with better gui

**Comment by hafeeluddeen** [comment]
Hi! can I contribute 4 in a row game coded in cpp?
